stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: ruby:2.7
  script:
    - echo "Building your Ruby application"
    - gem install bundler
    - bundle install --deployment --without development test
    - bundle exec rake assets:precompile

test:
  stage: test
  script:
    - echo "Running tests for your Ruby application"
    - bundle exec rake spec

deploy:
  stage: deploy
  script:
    - apt-get update && apt-get install -y python3-pip
    - pip3 install awsebcli --upgrade
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_REGION
    - eb init -p ruby-2.7 my-app-name --region $AWS_REGION
    - eb use my-app-name
    - eb deploy
