stages:
  - build
  - deploy

build:
  stage: build
  image: ruby:2.7
  script:
    - gem install bundler
    - bundle install --deployment --without development test
    - zip -r my-app.zip .

deploy:
  stage: deploy
  image: python:3.8
  before_script:
    - apt-get update && apt-get install -y python3-pip
    - pip3 install awsebcli --upgrade
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_REGION
    - eb init -p ruby-2.7 my-app-name --region $AWS_REGION
    - eb use my-app-name
    - eb deploy
